language: node_js
node_js:
- node
addons:
  apt:
    packages:
    - calibre
    - calibre-bin
before_install:
- npm install gitbook-cli -g
install:
- gitbook install
- npm install svgexport -g
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- gitbook pdf
- cp book.pdf ostap-tutorials.pdf
- gitbook build
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
    secure: EuJKKK+5fb8gwSCzZxXJc33xVGmLooQmOwdmW0EuX++Tz5+fkj0o5PYctGQyvQB+CMd6+a/G4IMXrXZC7qI2YksqWzuQtLoRVZnZ7KeGPMrvOdS8EFJ1ig+SCps2vdcPOiHcn1MsqxkPlJWFwi82OATmT4v6eyw0T/UQ0zFHnZhlKYT1FzMj3PQcZ6rWLI2jhI8JJW+7DVudsuqtiyICF+ORNJoDg2yXRmBqU4nTr6mCjQ/klx9fg81EIs5OdWs4UiTcrw0DdI7LjYrMXO1YrD/zhEplYxgOYz0ti/+8yJXUlMeR9JzV6fXb0pGkMqsck4gDIq1mfnD9qOjph737+qOh7yJk1KjBUIx0h30A5o7vryGsvEJcgJEBekRDStgn5Rug83TnWVAr34rS5adJt8A5EfwiIWOzNa3nx+FlUKxPFtlXYOLziRavF3tpXpyPmJ46xBoKWN+Xbq/vtBJKOEgf8y0MpZctlNkpRdBtGDKp0hxXH8JaWffqDB37y2tgS2Tp/dC7y/ONt0KlCjSwW1piL2pzqhMT+hZFIJeN65knW2ALlvWuItYeSxx894VXoPbCY9t8AKT+o84j/qV85l/vE4AeAl64oF5s5/vmy3OLAfOB8eVmdCC+PcNYPx+Y3ZaE2F1349BjMQ6rqwKOW2Z20rfLfG4txlc7p4jpAoQ=
